name: ac_lints
description: AC Lints rules
version: 0.5.0
repository: https://github.com/anthochamp/dart-lints

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.0.0
