name: ac_lints
description: AC Lints rules
version: 0.1.0
repository: https://github.com/anthochamp/dart-lints

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  dart_code_metrics: ^5.7.2
  flutter_lints: ^2.0.1
  lints: ^2.0.1
